services:
  main:
    container_name: main
    image: flight-dev
    build:
      context: .
      target: development
      # dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 8000:9000
    networks:
      - flight-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - flight-network
    restart: always
    # volumes:
    # - mongo-data:/var/lib/postgresql/data
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
volumes:
  mongo-data:
networks:
  flight-network:
